### ISSUE TITLE
Installation of Microsoft Visual C++ 2010 Redistributable Package is required

### ISSUE THREAD

**Issue by pischky** [subclipse/javahl-windows#1]
After installing eclipse and subclipse on a fresh Windows 7 system I got this error message while trying to access my repository:

```
Failed to load JavaHL Library.
These are the errors that were encountered:
no msvcp100 in java.library.path
C:\...\org.eclipse.osgi\476\0\.cp\libsvnjavahl-1.dll: Can't find dependent libraries
no svnjavahl-1 in java.library.path
no svnjavahl in java.library.path
java.library.path = C:\ProgramData\Oracle\Java\javapath;...;.
```

After installing the **Microsoft Visual C++ 2010 Redistributable Package** (x86 and x64) all worked.
[](https://www.microsoft.com/en-US/download/details.aspx?id=5555)
[](https://www.microsoft.com/en-us/download/details.aspx?id=14632)

May be there should be a hint during installation!

Thanks, Martin

**Comment by markphip** [comment]
Thanks for reporting.  I had accidentally turned off Github notifications so missed a lot of activity but a pull request came in today that fixes this issue and I have published it.
